version: '3.8'
services: 
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    mem_limit: 2g
    user: 1000:1000
    ports:
      - "8083:8080"
    volumes:
      - ./jenkins_data:/var/jenkins_home
    networks:
      - net
    
networks:
  net: